const puestos = [
        "Jefe De Oficina",
        "Secretaria Ejecutiva A",
        "Técnico Especializado",
        "Coordinador de Unidad de Serv. Esp.",
        "Comandante de Región",
        "Técnico Superior",
        "Director General",
        "Jefe de Sist. Administrativos",
        "Coordinador General",
        "Subdirector General",
        "Director General del Organismo de Cuenca o Director General",
        "Gerente o Director Local",
        "Coordinador General o Director General del Organismo De Cuenca",
        "Subdirector General o Titular del Órgano Interno de Control",
        "Gerente o Director General Adjunto",
        "Director Local o Director General Adjunto",
        "Director de Área",
        "Subgerente o Director de Área",
        "Coordinador de Proyectos Transversales, Transparencia e Innovación o Director de Área",
        "Coordinador De Proyectos Transversales",
        "Jefe de Proyecto A o Subdirector de Área A",
        "Subdirector de Área B",
        "Jefe de Proyecto C o Subdirección de Área C",
        "Jefe de Proyecto A o Jefe de Distrito o Residente o Especializado o Subdirector de Área A",
        "Jefe de Departamento A o Subjefe de Distrito o Residente de Obra",
        "Jefe de Departamento A",
        "Jefe de Departamento B",
        "Enlace",
        "Supervisor Técnico",
        "Jefe de Oficina De Obras",
        "Coordinador de Ecosistemas",
];

export default puestos;