// UNIDADES ADMINISTRATIVAS
const unidadesAdmin = [
  "Dirección General",
  "Subdirección General de Administración",
  "Subdirección General de Administración del Agua",
  "Subdirección General de Infraestructura Hidroagrícola",
  "Subdirección General de Agua Potable, Drenaje y Saneamiento",
  "Subdirección General Jurídica",
  "Subdirección General de Planeación",
  "Subdirección General Técnica",
  "Coordinación General del Servicio Meteorológico Nacional",
  "Coordinación General de Recaudación y Fiscalización",
  "Coordinación General de Comunicación y Cultura del Agua",
  "Coordinación General de Atención de Emergencias y Consejos de Cuenca",
  "Coordinación General de Proyectos Especiales de Abastecimiento y Saneamiento",
  "Organismos de Cuenca Península de Baja California",
  "Organismos de Cuenca Noroeste",
  "Organismos de Cuenca Pacífico Norte",
  "Organismos de Cuenca Balsas",
  "Organismos de Cuenca Pacífico Sur",
  "Organismos de Cuenca Río Bravo",
  "Organismos de Cuenca Cuencas Centrales del Norte",
  "Organismos de Cuenca Lerma Santiago Pacífico",
  "Organismos de Cuenca Golfo Norte",
  "Organismos de Cuenca Golfo Centro",
  "Organismos de Cuenca Frontera Sur",
  "Organismos de Cuenca Península de Yucatán",
  "Organismos de Cuenca Aguas del Valle de México",
  "Dirección Local Aguascalientes",
  "Dirección Local Baja California Sur",
  "Dirección Local Campeche",
  "Dirección Local Coahuila",
  "Dirección Local Colima",
  "Dirección Local Chihuahua",
  "Dirección Local Durango",
  "Dirección Local Guanajuato",
  "Dirección Local Guerrero",
  "Dirección Local Hidalgo",
  "Dirección Local Estado de México",
  "Dirección Local Michoacán",
  "Dirección Local Nayarit",
  "Dirección Local Puebla",
  "Dirección Local Querétaro",
  "Dirección Local Quintana Roo",
  "Dirección Local San Luis Potosí",
  "Dirección Local Tabasco",
  "Dirección Local Tlaxcala",
  "Dirección Local Zacatecas",
];

export default unidadesAdmin;
