// UNIDADES ADMINISTRATIVAS
const unidadesAdmin = [
  "Dirección General",
  "Coordinación General De Comunicación Y Cultura Del Agua",
  "Coordinación General De Recaudación Y Fiscalización",
  "Subdirección General Jurídica",
  "Subdirección General De Administración Del Agua",
  "Subdirección General De Agua Potable Drenaje Y Saneamiento",
  "Dirección General Del Parque Ecológico Lago De Texcoco",
  "Subdirección General De Infraestructura Hidroagrícola",
  "Subdirección General Técnica",
  "Coordinación General Del Servicio Meteorológico Nacional",
  "Subdirección General De Administración",
  "Organismo De Cuenca Aguas Del Valle De México",
  "Organismo De Cuenca Cuencas Centrales Del Norte",
  "Organismo De Cuenca Noroeste",
  "Organismo De Cuenca Golfo Norte",
  "Organismo De Cuenca Golfo Centro",
  "Organismo De Cuenca Península De Yucatán",
  "Organismo De Cuenca Península De Baja California",
  "Organismo De Cuenca Pacifico Norte",
  "Organismo De Cuenca Balsas",
  "Organismo De Cuenca Pacífico Sur",
  "Organismo De Cuenca Rio Bravo",
  "Organismo De Cuenca Lerma Santiago Pacífico",
  "Organismo De Cuenca Frontera Sur",
  "Dirección Local Aguascalientes",
  "Dirección Local Baja California Sur",
  "Dirección Local Campeche",
  "Dirección Local Chihuahua",
  "Dirección Local Coahuila",
  "Dirección Local Colima",
  "Dirección Local Durango",
  "Dirección Local Guanajuato",
  "Dirección Local Guerrero",
  "Dirección Local Hidalgo",
  "Dirección Local Estado De México",
  "Dirección Local Michoacán",
  "Dirección Local Nayarit",
  "Dirección Local Puebla",
  "Dirección Local Querétaro",
  "Dirección Local Quintana Roo",
  "Dirección Local San Luis Potosí",
  "Dirección Local Tabasco",
  "Dirección Local Tlaxcala",
  "Dirección Local Zacatecas",

];

export default unidadesAdmin;
